In [ ]:
# First Project : Predict Student Marks Based On Number Of Hours Studied

# import all the necessary libraries
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# Step 1 : Data Gathering
data = pd.read_csv('https://raw.githubusercontent.com/yash240990/Python/master/Grade_Set_1.csv')
data

   Hours_Studied  Test_Grade Status Result
0              2          57   fail      D
1              3          66   fail      D
2              4          73   pass      C
3              5          76   pass      C
4              6          79   pass      C
5              7          81   pass      B
6              8          90   pass      B
7              9          96   pass      A
8             10         100   pass      A

In [ ]:
# Step 2 : EDA
data.shape

(9, 4)

In [ ]:
data.columns

Index(['Hours_Studied', 'Test_Grade', 'Status', 'Result'], dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Hours_Studied  9 non-null      int64
 1   Test_Grade     9 non-null      int64
 2   Status         9 non-null      object
 3   Result         9 non-null      object
dtypes: int64(2), object(2)
memory usage: 420.0+ bytes

In [ ]:
# Step 3 : Data Preparation
# a.) check for missing and duplicate values
# b.) convert non-numerical features into numerical features
# c.) normalization
# d.) select independent and dependent variable

In [ ]:
# a.) check for missing and duplicate values
data.isnull().sum()

Hours_Studied    0
Test_Grade       0
Status           0
Result           0
dtype: int64

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
# b.) convert non-numerical features into numerical features
import sklearn.preprocessing as pp
lb = pp.LabelBinarizer()

In [ ]:
# LabelBinarizer neg_label  --> int, default=0    pos_label --> int, default=1
print(lb.fit_transform(['fail','pass']))
print(lb.fit_transform(['true','false']))
print(lb.fit_transform(['yes','no']))
print(lb.fit_transform(['positive','negative']))
print(lb.fit_transform(['success','no success']))

[[0]
 [1]]
[[1]
 [0]]
[[1]
 [0]]
[[1]
 [0]]
[[1]
 [0]]

In [ ]:
data.Status = lb.fit_transform(data.Status)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Hours_Studied  9 non-null      int64
 1   Test_Grade     9 non-null      int64
 2   Status         9 non-null      int64
 3   Result         9 non-null      object
dtypes: int64(3), object(1)
memory usage: 420.0+ bytes

In [ ]:
# c.) normalization
# Normalization is a data preprocessing step in machine learning where we adjust
# the scale of numeric features so that they fall within a similar range (usually
# between 0 and 1, or –1 and 1).

# normalize these numbers for me
# numbers = [57,  66,  73,  76,  79,  81,  90,  96, 100]

# Xnorm = (X-Xmin) / (Xmax - Xmin)        known as Min-Max Scaling
# Xmin = 57
# Xmax = 100
# X = 96  and X = 100

# Xnorm = ??


# 57 --> 0
# 96 --> 0.9
# 100 --> 1

In [ ]:
vals = data.Test_Grade.values
print(vals)

normalized_values = pp.normalize([vals])
print(normalized_values)

min_max_sc = pp.MinMaxScaler()
normalized_values1 = min_max_sc.fit_transform([vals])
print(normalized_values1)

[ 57  66  73  76  79  81  90  96 100]
[[0.23500809 0.27211463 0.30097527 0.31334412 0.32571297 0.33395887
  0.37106541 0.3958031  0.4122949 ]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]]

In [ ]:
# d.) select independent and dependent variable
x = data.Hours_Studied.values
x = x.reshape(9,1)
print(x)

[[ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]

In [ ]:
y = data.Test_Grade.values
print(y)

[ 57  66  73  76  79  81  90  96 100]

In [ ]:
# Step 4 : Model Development
# Apply A Suitable ML Algo On Dataset

import sklearn.linear_model as lm
lin_reg = lm.LinearRegression()

In [ ]:
lin_reg.fit(x,y)

LinearRegression()

In [ ]:
'''
Using Pickle

Using pickle in machine learning is mainly about saving and loading trained models in Python so you don’t have to retrain them every time.


Why use pickle in Machine Learning?

When you train a model (e.g. using scikit-learn), training can take time. Instead of retraining:

Save the model once
Load it later for predictions'''

print('Using Pickle')

import pickle
# dump() is used to save ML Model
# pickle uses bytestream format
pickle.dump(lin_reg,open('slrname.pkl','wb')) # w --> write / create a file  b --> bytestream

Using Pickle

In [ ]:
# Step 5 : Evaluate Our Model Performance
data['predictedValues'] = lin_reg.predict(x)

In [ ]:
data[['Hours_Studied','Test_Grade','predictedValues']]

   Hours_Studied  Test_Grade  predictedValues
0              2          57        59.711111
1              3          66        64.727778
2              4          73        69.744444
3              5          76        74.761111
4              6          79        79.777778
5              7          81        84.794444
6              8          90        89.811111
7              9          96        94.827778
8             10         100        99.844444